version: "3.7"

services:
  db:
    image: postgres
    container_name: firestar-db-dev
    networks:
      - webnet
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: firestar_test
      NODE_ENV: development
      DB_HOST: localhost
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet
  server:
    image: firestar-backend
    container_name: firestar-server-dev
    build: .
    env_file: .env
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4001:4000
      - 9229:9229
    depends_on:
      - db
    links:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: firestar_test
      NODE_ENV: development
      DB_HOST: postgres
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - webnet
networks:
  webnet:
volumes:
  entrypoint.sh:
