version: "3.7"

services:
  db:
    image: postgres
    networks:
      - webnet
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${DATABASE_URL_TEST}
    volumes:
      - ./pgdata:/var/
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: npm start
  server:
    image: firestar-backend
    build: .
    env_file:
      - .env
    environment:
      API_HOST: ${API_HOST}
      API_SERVER_PORT: ${SERVER_PORT}
      DB_HOST: db
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    depends_on:
      - "db"
    links:
      - db
    networks:
      - webnet
    command: npm start:dev
networks:
  webnet:
